# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c8d3e58e8cada0a9ca95bf13d7b2dd98c648a3dc540e43a46eb8ab927c2c068d8a6809f68890a1453b6b459bd02f210cdb00e8dc6c260cc57a3a8d4ee778268

test:
  secret_key_base: 7062bf59e74993c385e9964230fb8fe87fe6184390ca7960454bd7c41d53c18b0d115b4416a345ed63111dca9c68341c50053b90ec80d808068f3873caa00606

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
